"""
Stage 6: LLM Review Findings Verifier via TypeSafe Jev.

Filters hallucinations, false positives, and misinterpretations generated by LLM
reviewers by evaluating the reviewer's claim against the cited code context.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from .jev import ask_jev

FINDING_VERIFIER_QUESTIONS: Dict[str, Dict[str, Any]] = {
    "claim_supported_by_code": {
        "type": "noul",
        "instructions": (
            "A code reviewer analyzed `{file}:{line}` in `{function}` and made this defect claim:\n"
            "Claim: `{claim}`\n\n"
            "Examining strictly the code excerpt in `cited_code`: does the code genuinely contain or exhibit this defect? "
            "Does the code behave as the reviewer claims, or is the claim a false alarm, hallucination, or invalid assumption?"
        ),
        "criteria": {
            "true": "The cited code genuinely contains the bug, flaw, or contract violation described.",
            "false": "The claim is false, misinterprets the code, hallucinates an issue that cannot occur, or is an invalid concern.",
        },
    },
    "severity": {
        "type": "choice",
        "instructions": "If this finding is valid, how should its severity be classified?",
        "criteria": {
            "critical": "Crashes, security vulnerability, data loss, or silent corruption.",
            "major": "Broken business logic, regression, or unhandled edge case for plausible inputs.",
            "minor": "Defensive check, low-probability edge case, or code cleanup.",
            "false_alarm": "Not a bug; intentional design, stylistic complaint, or invalid finding.",
        },
    },
}


def finding_state(finding: Any, cited_code: str) -> Dict[str, Any]:
    """Packages finding claim and cited code into an evidence-first state."""
    file_path = getattr(finding, "file", None) or (finding.get("file") if isinstance(finding, dict) else "")
    line_no = getattr(finding, "line", None) or (finding.get("line") if isinstance(finding, dict) else 0)
    function_name = getattr(finding, "function", None) or (finding.get("function") if isinstance(finding, dict) else "")
    claim_text = getattr(finding, "claim", None) or (finding.get("claim") if isinstance(finding, dict) else "")

    return {
        "file": file_path,
        "line": line_no,
        "function": function_name,
        "claim": claim_text,
        "cited_code": cited_code[:32_000],
    }


def verify_finding_with_jev(
    api_key: str,
    finding: Any,
    cited_code: str,
    threshold: float = 0.6,
    timeout: int = 45,
) -> Dict[str, Any]:
    """
    Verifies an LLM review finding against the cited code using Jev.
    """
    state = finding_state(finding, cited_code)
    resp = ask_jev(api_key, state, FINDING_VERIFIER_QUESTIONS, timeout=timeout)

    if "error" in resp:
        return {
            "is_valid": None,
            "support_probability": None,
            "calibrated_severity": "unknown",
            "verdict": "UNKNOWN",
            "usage": resp.get("usage", {}),
            "error": resp["error"],
        }

    answers = resp.get("answers", {})
    prob = float((answers.get("claim_supported_by_code") or {}).get("noul", 0.0))
    severity_choice = str((answers.get("severity") or {}).get("choice", "minor"))

    is_valid = (prob >= threshold) and (severity_choice != "false_alarm")
    verdict = "VALID" if is_valid else "FALSE_ALARM"

    return {
        "is_valid": is_valid,
        "support_probability": prob,
        "calibrated_severity": severity_choice,
        "verdict": verdict,
        "usage": resp.get("usage", {}),
    }
